[project]
name = "study-buddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.133.1",
    "pydantic>=2.12.5",
    "pymongo>=4.16.0",
    "uvicorn>=0.41.0",
]
